require("gitsigns").setup({})
vim.keymap.set("n", "<leader>gf", "<cmd>Git<cr>", { desc = "Open [F]ugitive" })
vim.keymap.set("n", "<leader>gd", function()
	require("gitsigns").diffthis()
end, { desc = "[D]iff file" })
vim.keymap.set("n", "<leader>gs", function()
	require("gitsigns").stage_hunk()
end, { desc = "Toggle [S]tage hunk" })
vim.keymap.set("n", "<leader>gr", function()
	require("gitsigns").reset_hunk()
end, { desc = "reset hunk" })
vim.keymap.set("n", "<leader>gp", function()
	require("gitsigns").preview_hunk()
end, { desc = "[P]review hunk" })
vim.keymap.set("n", "<leader>gb", function()
	require("gitsigns").toggle_current_line_blame()
end, { desc = "Toggle current line [B]lame" })
vim.keymap.set("n", "[g", function()
	require("gitsigns").nav_hunk("prev")
end, { desc = "Go previous git hunk" })
vim.keymap.set("n", "]g", function()
	require("gitsigns").nav_hunk("next")
end, { desc = "Go next git hunk" })
