#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true
    [[blocks.segments]]
        type = 'path'
        style = 'plain'
        foreground = 'p:blue'
        template = '{{ .Path }}'

        [blocks.segments.properties]
            style = 'full'

    [[blocks.segments]]
        type = "git"
        style = "plain"
        foreground = "p:overlay0"
        template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

        [properties]
        fetch_status = true
        fetch_upstream_icon = true
        source = "cli"

[[blocks]]
    type = 'rprompt'
    overflow = 'hidden'

    [[blocks.segments]]
        type='executiontime'
        style = 'plain'
        foreground = 'p:peach'
        template = '{{ div .Ms 1000 }}s'
       
        [blocks.segments.properties]
            threshold = 2000

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        type = 'text'
        style = 'plain'
        foreground_templates = [
            "{{if gt .Code 0}}p:red{{end}}",
            "{{if eq .Code 0}}p:green{{end}}",
        ]
        template = 'λ'

[palette]
    rosewater = "#F5E0DC"
    flamingo = "#F2CDCD"
    pink = "#F5C2E7"
    mauve = "#CBA6F7"
    red = "#F38BA8"
    maroon = "#EBA0AC"
    peach = "#FAB387"
    yellow = "#F9E2AF"
    green = "#A6E3A1"
    teal = "#94E2D5"
    sky = "#89DCEB"
    sapphire = "#74C7EC"
    blue = "#89B4FA"
    lavender = "#B4BEFE"
    text = "#CDD6F4"
    subtext1 = "#BAC2DE"
    subtext0 = "#A6ADC8"
    overlay2 = "#9399B2"
    overlay1 = "#7F849C"
    overlay0 = "#6C7086"
    surface2 = "#585B70"
    surface1 = "#45475A"
    surface0 = "#313244"
    base = "#1E1E2E"
    mantle = "#181825"
    crust = "#11111B"
    
[transient_prompt]
    foreground_templates = [
        "{{if gt .Code 0}}p:red{{end}}",
        "{{if eq .Code 0}}p:green{{end}}",
    ]
    template = 'λ '
