console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  base = '#1E1E2E'
  blue = '#89B4FA'
  crust = '#11111B'
  flamingo = '#F2CDCD'
  green = '#A6E3A1'
  lavender = '#B4BEFE'
  mantle = '#181825'
  maroon = '#EBA0AC'
  mauve = '#CBA6F7'
  overlay0 = '#6C7086'
  overlay1 = '#7F849C'
  overlay2 = '#9399B2'
  peach = '#FAB387'
  pink = '#F5C2E7'
  red = '#F38BA8'
  rosewater = '#F5E0DC'
  sapphire = '#74C7EC'
  sky = '#89DCEB'
  subtext0 = '#A6ADC8'
  subtext1 = '#BAC2DE'
  surface0 = '#313244'
  surface1 = '#45475A'
  surface2 = '#585B70'
  teal = '#94E2D5'
  text = '#CDD6F4'
  yellow = '#F9E2AF'

[transient_prompt]
  template = 'λ '
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:blue'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }}'
    foreground = 'p:overlay0'
    type = 'git'
    style = 'plain'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ div .Ms 1000 }}s'
    foreground = 'p:peach'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 2000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = 'λ'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:green{{end}}']

